gfx/env/shacks_up.tga
gfx/env/shacks_dn.tga
gfx/env/shacks_lf.tga
gfx/env/shacks_rt.tga
gfx/env/shacks_ft.tga
gfx/env/shacks_bk.tga
sprites/xsmoke1.spr
models/props_vehicles/boat_covered.mdl
sprites/glow01.spr
models/props_furniture/fridge002.mdl
models/props_foliage/pred_mal.mdl
models/props_foliage/palm2.mdl
models/props_foliage/shrub_jungles.mdl
sound/doors/wood_open.wav
models/props_bank/de_bank_csgo/hydrant_yellow.mdl
sprites/2dprops/travks.spr
models/zp_models/zp_light/zp_light05.mdl
models/props_dust/awnings.mdl
models/props_urban/barrier001_96.mdl
models/props_vehicles/boat_cabin35.mdl
models/props_shacks/piling_cluster.mdl
models/props_bank/p2_electrical_boxes.mdl
sprites/de_nust2/glow.spr
models/props_pipes/gutter_512_001a.mdl
models/props_rooftop/electric_cables.mdl
models/props_rooftop/antenna03a.mdl
models/props_shacks/barier.mdl
models/props_shacks/buoys.mdl
models/props_urban/porch_light003.mdl
models/props_shacks/shacks_boatbar.mdl
models/props_urban/bench01.mdl
models/safehouse/hessi_big_baum.mdl
models/props_foliage/palm.mdl
sound/ambient/machines/truck_idle_lp_01.wav
models/props_bank/bag2.mdl
models/props_bank/bag1.mdl
sprites/2dprops/uvine02.spr
models/props/acunit02.mdl
models/de_train_csgo/acunit01.mdl
models/props_furniture/sink_industrial01.mdl
models/props_rooftop/scaffolding1a.mdl
models/props_shacks/flag_pole.mdl
models/props_shacks/shacks_sbeams.mdl
models/props_shacks/group_objects1.mdl
models/props_vehicles/fishing_boat.mdl
sprites/2dprops/misc_wire_g.spr
sprites/2dprops/decalrug.spr
sprites/2dprops/palmline.spr
sprites/2dprops/treepalm.spr
models/props_bank/csgo_cars/84_sedan.mdl
models/props_bank/csgo_cars/69_sedan.mdl
models/props_lake/boat002.mdl
sprites/2dprops/tube.spr
sprites/2dprops/palm.spr
models/laguna/gins_gull.mdl
models/props_furniture/wood_porchsteps.mdl
sound/de_dockland/mer.wav
sound/ambient/atmosphere/dock_lp_01.wav
sound/ambient/wind/flag_and_rope_loop.wav
sound/ambient/atmosphere/shack_belize_birds_lp_01.wav
sound/de_season_css/radio_pilot.wav
sound/de_season_css/radio.wav
